// Code generated from auth.proto — do NOT edit manually.
// In a real project, run: protoc --go_out=. --go-grpc_out=. shared/protos/auth.proto
// This file represents the generated gRPC client stub.

package authpb

import (
	"context"
	"time"

	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/keepalive"
)

// TokenPayload contains the decoded JWT claims from auth-service
type TokenPayload struct {
	Valid   bool
	UserID  string
	Email   string
	Tier    string
}

// AuthClient — gRPC client for calling auth-service from url-service
//
// Connection lifecycle:
//   - Single persistent HTTP/2 connection (multiplexed — no per-request overhead)
//   - KeepAlive pings every 30s to detect dead connections
//   - Timeout: 500ms per RPC call (fail fast on auth service outage)
//
// Why HTTP/2 multiplexing matters:
//   With REST, each call needs a new TCP connection (or waits on the pool).
//   With gRPC over HTTP/2, thousands of concurrent RPCs share a single connection.
type AuthClient struct {
	conn   *grpc.ClientConn
	logger *zap.Logger
}

// NewAuthClient creates a new gRPC connection to auth-service
func NewAuthClient(target string, logger *zap.Logger) (*AuthClient, error) {
	conn, err := grpc.NewClient(
		target,
		grpc.WithTransportCredentials(insecure.NewCredentials()), // TLS at service mesh level
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                30 * time.Second,
			Timeout:             10 * time.Second,
			PermitWithoutStream: true,
		}),
	)
	if err != nil {
		return nil, err
	}

	return &AuthClient{conn: conn, logger: logger}, nil
}

// VerifyToken calls auth-service over gRPC to validate a JWT.
// Returns the decoded payload or an error if the token is invalid.
func (c *AuthClient) VerifyToken(ctx context.Context, accessToken string) (*TokenPayload, error) {
	// Tight 500ms deadline — auth check must be fast or we fail the request
	ctx, cancel := context.WithTimeout(ctx, 500*time.Millisecond)
	defer cancel()

	// In a real project, this would use the generated gRPC stub.
	// The structure below mirrors exactly what the generated code does.
	req := &VerifyTokenRequest{AccessToken: accessToken}
	resp, err := c.rawVerifyToken(ctx, req)
	if err != nil {
		c.logger.Warn("gRPC VerifyToken call failed", zap.Error(err))
		return nil, err
	}

	return &TokenPayload{
		Valid:  resp.Valid,
		UserID: resp.UserId,
		Email:  resp.Email,
		Tier:   resp.Tier,
	}, nil
}

// Close tears down the gRPC connection cleanly on service shutdown
func (c *AuthClient) Close() error {
	return c.conn.Close()
}

// ── Stub types (normally generated by protoc) ─────────────────────────

type VerifyTokenRequest struct {
	AccessToken string
}

type VerifyTokenResponse struct {
	Valid   bool
	UserId  string
	Email   string
	Tier    string
}

// rawVerifyToken represents the generated RPC invocation stub
func (c *AuthClient) rawVerifyToken(ctx context.Context, req *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	// Normally: return c.stub.VerifyToken(ctx, req)
	// Since protoc is not in this environment, this shows the pattern clearly.
	// The actual generated code is identical in structure to this.
	var resp VerifyTokenResponse
	err := c.conn.Invoke(ctx, "/auth.AuthService/VerifyToken", req, &resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
